url: "https://arcana.computer" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "arcana dot computer" # the name of your site, e.g. ACME Corp.
collections:
    industry:
        output: true
        permalink: /:collection/:name
    engineering:
        output: true
        permalink: /:collection/:name
    products:
        output: true
        permalink: /:collection/:name
    mortems:
        output: true
        permalink: /:collection/:name
    miscellany:
        output: true
        permalink: /:collection/:name
    catalogs:
        output: true
        permalink: /:collection/:name
collections_dir: writing
description: "Arcana Dot Computer is a web site about engineering and personality by Justin Duke."